### ISSUE TITLE
Versioned test suite

### ISSUE THREAD

**Issue by jayvdb** [ClericPy/torequests#14]
The PyPI releases do not include tests, and there are no GitHub releases, so I can not get a stable URL for fetching tests of a release

**Comment by ClericPy** [comment]
For now I use **pytest** as an interim solution
`python3 -m pytest -v`
`python2 -m pytest -v`

These days I would like to launch Travis CI for a choice.

Although I used this lib in product environment, there sometimes raise an unexpected issue. So the stable version may be released after:
1. Travis CI support
2. python3.8 released for the aiohttp deprecated
3. `httpx` would take place of `aiohttp`, for the latter often take a not backward compatible api variable name. Now waiting for `httpx`'s websocket support

Thanks for your opinion, I maybe refactor the main.py for some unreadable code in the future.

aiohttp / lxml test warning
```
 DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Mapping, Sequence, deque
```
